# Generated by Django 5.2.3 on 2025-06-30 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='todo',
        ),
    ]
